export const NOTIFICATION_TYPES = {
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_COMPLETED: "BOOKING_COMPLETED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  REQUEST_NEW_RESPONSE: "REQUEST_NEW_RESPONSE",
  REQUEST_RESPONSE_ACCEPTED: "REQUEST_RESPONSE_ACCEPTED",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  KYC_PENDING: "KYC_PENDING",
  KYC_APPROVED: "KYC_APPROVED",
  KYC_REJECTED: "KYC_REJECTED",
  EQUIPMENT_APPROVED: "EQUIPMENT_APPROVED",
  EQUIPMENT_REJECTED: "EQUIPMENT_REJECTED",
  RENTAL_REQUESTED: "RENTAL_REQUESTED",
  RENTAL_ACCEPTED: "RENTAL_ACCEPTED",
  RENTAL_PAID: "RENTAL_PAID",
  RENTAL_RETURN_REQUESTED: "RENTAL_RETURN_REQUESTED",
  RENTAL_COMPLETED: "RENTAL_COMPLETED",
  RENTAL_DISPUTED: "RENTAL_DISPUTED",
} as const;

export type NotificationType =
  (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];

const EMAIL_NOTIFICATION_TYPES = new Set<NotificationType>([
  NOTIFICATION_TYPES.MESSAGE_RECEIVED,
  NOTIFICATION_TYPES.KYC_PENDING,
  NOTIFICATION_TYPES.KYC_APPROVED,
  NOTIFICATION_TYPES.KYC_REJECTED,
  NOTIFICATION_TYPES.EQUIPMENT_APPROVED,
  NOTIFICATION_TYPES.EQUIPMENT_REJECTED,
  NOTIFICATION_TYPES.RENTAL_REQUESTED,
  NOTIFICATION_TYPES.RENTAL_ACCEPTED,
  NOTIFICATION_TYPES.RENTAL_PAID,
  NOTIFICATION_TYPES.RENTAL_COMPLETED,
  NOTIFICATION_TYPES.RENTAL_DISPUTED,
]);

export function sendsNotificationEmail(type: NotificationType): boolean {
  return EMAIL_NOTIFICATION_TYPES.has(type);
}
